### ISSUE TITLE
Specifying just one of -s, -c yields TypeScript compilation errors

### ISSUE THREAD

**Issue by arielshaqed** [binaris/concord#8]
Each writes code that requires the other's dependencies.

# `-c fetch` with no `-s` fails
```
flutterby:interfaces ariels$ ./node_modules/.bin/concord -o ./gen node -c fetch foo@0.0.1 v2.ts
npm WARN foo@0.0.1 No license field.

removed 74 packages and audited 14 packages in 1.106s
found 0 vulnerabilities

src/koaMW.ts:2:28 - error TS2307: Cannot find module 'koa-router'.

2 import * as koaRouter from 'koa-router';
                             ~~~~~~~~~~~~

src/koaMW.ts:3:26 - error TS2307: Cannot find module 'koa-bodyparser'.

3 import * as koaBody from 'koa-bodyparser'; // tslint:disable-line:no-unused-variable
                           ~~~~~~~~~~~~~~~~

src/server.ts:3:22 - error TS2307: Cannot find module 'koa'.

3 import * as Koa from 'koa';
                       ~~~~~

src/server.ts:4:25 - error TS2307: Cannot find module 'koa-router'.

4 import * as Router from 'koa-router';
                          ~~~~~~~~~~~~

src/server.ts:5:29 - error TS2307: Cannot find module 'koa-bodyparser'.

5 import * as bodyParser from 'koa-bodyparser';
                              ~~~~~~~~~~~~~~~~

src/server.ts:41:54 - error TS7006: Parameter 'ctx' implicitly has an 'any' type.

41     this.koaRouter.post('/reportConcurrency', async (ctx) => {
                                                        ~~~


Found 6 errors.

Failed to generate files:
Error: command: 'tsc' failed process failed with exit code: 2
    at ChildProcess.child.on (/Users/ariels/Google Drive/Work/Dev/xenu/interfaces/node_modules/concord/dist/utils.js:12:20)
    at ChildProcess.emit (events.js:197:13)
    at maybeClose (internal/child_process.js:984:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
```

# `-s koa` with no `-c` fails
```
flutterby:interfaces ariels$ ./node_modules/.bin/concord -o ./gen node -s koa foo@0.0.1 v2.ts
npm WARN foo@0.0.1 No license field.

added 74 packages from 67 contributors, removed 4 packages and audited 174 packages in 2.741s
found 0 vulnerabilities

src/client.ts:2:19 - error TS2307: Cannot find module 'node-fetch'.

2 import fetch from 'node-fetch';
                    ~~~~~~~~~~~~

src/client.ts:3:29 - error TS2307: Cannot find module 'node-fetch'.

3 import { RequestInit } from 'node-fetch';
                              ~~~~~~~~~~~~

src/client.ts:4:29 - error TS2307: Cannot find module 'abort-controller'.

4 import AbortController from 'abort-controller';
                              ~~~~~~~~~~~~~~~~~~

src/client.ts:47:60 - error TS2739: Type '{}' is missing the following properties from type 'Options': follow, agent, redirect, compress

47   public constructor(protected readonly serverUrl: string, protected readonly options: Options = {}) {
                                                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Found 4 errors.

Failed to generate files:
Error: command: 'tsc' failed process failed with exit code: 2
    at ChildProcess.child.on (/Users/ariels/Google Drive/Work/Dev/xenu/interfaces/node_modules/concord/dist/utils.js:12:20)
    at ChildProcess.emit (events.js:197:13)
    at maybeClose (internal/child_process.js:984:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
```

**Comment by arielshaqed** [comment]
This is caused by leftovers from previous runs in the directory: it doesn't clean the output directory (good!), but then it tries to compile everything in the directory (and fails).  To reproduce, clean the directory, run `-c fetch`, then run `-s koa` (fails), and then `-c fetch` again (also fails).

**Comment by bergundy** [comment]
That makes sense, it should not work.
What would improve the experience in this case?

**Comment by bergundy** [comment]
@arielshaqed maybe we should let `concord` create the directory and complain if it already exists?

**Comment by arielshaqed** [comment]
> @arielshaqed maybe we should let `concord` create the directory and complain if it already exists?

That is inconvenient for a development cycle.

More alternatives:
* Separate client and server directories.
* Explicitly list files in compilation commands.
* Moar `devDependencies` in the generated `package.json` to support client and server no matter what.  (Would that even work?)

**Comment by bergundy** [comment]
Not necessarily inconvenient, we could `rm -rf gen && concord ...` instead of `mkdir -p gen && concord` like we do today.
That guarantees no junk is left in that generated code dir.
@vogre do you have an opinion here?

**Comment by vogre** [comment]
We could write a file with the generated code with the command line arguments used to generate it. If the command line arguments don't match ask the user to remove the folder.

Maybe even simpler, since we have a list of file that we generate we can remove *all other files*.

**Comment by bergundy** [comment]
I'm leaning toward creating the directory for the user and complaining in case it exists, I would rather not delete anything since users might put other files in the generated folder.

**Comment by arielshaqed** [comment]
We _could_ declare it PEBCAK ~and suggest in the README `-o gen.client` and `-o gen.server`~ -- the README suggests using separate `-o` directories for client and server.  ~@bergundy I'll send a PR.~

**Comment by bergundy** [comment]
Let's go for having `concord` create the directory and complain unless it exists.
